CREATE SCHEMA IF NOT EXISTS testdb;

USE testdb;

CREATE TABLE IF NOT EXISTS building (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  out_of_order BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS company (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  building_id BIGINT NOT NULL,
  num_emp INT NOT NULL,
  FOREIGN KEY (building_id) REFERENCES building(id)
);

CREATE TABLE IF NOT EXISTS employee (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  company_id BIGINT NOT NULL,
  FOREIGN KEY (company_id) REFERENCES company(id)
);
